### PR TITLE
Minor improvements in the `README.md` file

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Minor improvements in the `README.md` file.
  - All the changes are shown in the Git diff. If you have any questions about them, please let me know below. 🙂

### CODE REVIEW

**Review by bharadwajduggaraju — APPROVED** [review]

**Comment by bharadwajduggaraju** [comment]
Seems that you just added a line to the README. Could you explain to me what that line does? Once you do, I can merge your changes! And if you like my work, a follow would me hugely appreciated

**Comment by Panquesito7** [comment]
> Seems that you just added a line to the README. Could you explain to me what that line does? Once you do, I can merge your changes! And if you like my work, a follow would me hugely appreciated

Hey there! What line are you referring to?

**Comment by bharadwajduggaraju** [comment]
image
Seems like this is the line you added. I'm wondering what it does.

**Comment by Panquesito7** [comment]
> image Seems like this is the line you added. I'm wondering what it does.

Ahh, that's for the Markdown Linter to ignore the following line. Markdown Linter is a tool that checks if your Markdown file meets the requirements and that there are no warnings. 🙂

https://github.com/markdownlint/markdownlint

**Comment by bharadwajduggaraju** [comment]
Is that it for the changes you made. If so, I can merge them in.

**Comment by Panquesito7** [comment]
> Is that it for the changes you made. If so, I can merge them in.

What do you mean exactly?

**Comment by bharadwajduggaraju** [comment]
I'm just wondering if you made any other changes besides the line for the linting.

**Comment by Panquesito7** [comment]
> I'm just wondering if you made any other changes besides the line for the linting.

Yes, I removed 4 extra lines at the end which fixed another Markdown Linter warning.

**Comment by bharadwajduggaraju** [comment]
Sweet, I'll merge your changes

**Comment by bharadwajduggaraju** [comment]
thanks for helping, and if you like any of my work feel free to star or leave a follow. once again thanks for the help, this is my first PR!

**Pull request merged**
